pipeline:
  name: harness as code
  identifier: harness_as_code
  projectIdentifier: Default_Project_1662659562703
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: aws creds
        identifier: aws_creds
        template:
          templateRef: account.generate_and_save_aws_keys
          versionLabel: "1"
          gitBranch: main
    - stage:
        name: tf
        identifier: tf
        description: ""
        type: IACM
        spec:
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 5m
                  spec:
                    command: init
              - step:
                  name: tflint
                  identifier: tflint
                  template:
                    templateRef: account.tflint
                    versionLabel: 0.0.1
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 5m
                  spec:
                    command: plan
              - parallel:
                  - step:
                      name: checkov
                      identifier: checkov
                      template:
                        templateRef: account.checkov
                        versionLabel: 0.0.1
                  - step:
                      name: tfsec
                      identifier: tfsec
                      template:
                        templateRef: account.tfsec
                        versionLabel: 0.0.1
              - step:
                  type: IACMApproval
                  name: approve
                  identifier: approve
                  spec: {}
                  timeout: 5m
                  when:
                    stageStatus: Success
                    condition: <+trigger.event> != "PR"
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  timeout: 5m
                  spec:
                    command: apply
                  when:
                    stageStatus: Success
                    condition: <+trigger.event> != "PR"
          workspace: harnessinfra
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        tags: {}
        delegateSelectors:
          - ecs
