pipeline:
  name: harness as code
  identifier: harness_as_code
  projectIdentifier: Default_Project_1662659562703
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: apply
        identifier: apply
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: assume
                  identifier: assume
                  template:
                    templateRef: account.aws_assume_sales_admin
                    versionLabel: "1"
              - step:
                  type: TerraformPlan
                  name: plan
                  identifier: pla
                  spec:
                    configuration:
                      command: Apply
                      configFiles:
                        store:
                          type: Github
                          spec:
                            gitFetchType: Branch
                            connectorRef: account.gitssh
                            repoName: harness-infra
                            branch: <+input>
                            folderPath: foobar/
                        moduleSource:
                          useConnectorCredentials: true
                      environmentVariables:
                        - name: AWS_REGION
                          value: us-west-2
                          type: String
                        - name: AWS_ACCESS_KEY_ID
                          value: <+execution.steps.assume.output.outputVariables.AWS_ACCESS_KEY_ID>
                          type: String
                        - name: AWS_SECRET_ACCESS_KEY
                          value: <+execution.steps.assume.output.outputVariables.AWS_SECRET_ACCESS_KEY>
                          type: String
                        - name: HARNESS_PLATFORM_API_KEY
                          value: <+secrets.getValue("account.harness_api_token")>
                          type: String
                        - name: HARNESS_ACCOUNT_ID
                          value: wlgELJ0TTre5aZhzpt8gVA
                          type: String
                        - name: AWS_SESSION_TOKEN
                          value: <+execution.steps.assume.output.outputVariables.AWS_SESSION_TOKEN>
                          type: String
                        - name: ARM_TENANT_ID
                          value: b229b2bb-5f33-4d22-bce0-730f6474e906
                          type: String
                        - name: ARM_SUBSCRIPTION_ID
                          value: e8389fc5-0cb8-44ab-947b-c6cf62552be0
                          type: String
                        - name: ARM_CLIENT_ID
                          value: 78ff246f-45e4-4f96-95e8-6f8549435b26
                          type: String
                        - name: ARM_CLIENT_SECRET
                          value: <+secrets.getValue("account.azure")>
                          type: String
                      varFiles:
                        - varFile:
                            spec:
                              content: vscode_password = "<+secret.getValue("vscode_password")>"
                            identifier: inputs
                            type: Inline
                      secretManagerRef: harnessSecretManager
                      skipRefreshCommand: false
                    provisionerIdentifier: harnessascode
                  timeout: 10m
              - step:
                  type: Http
                  name: plan pr
                  identifier: plan_pr
                  spec:
                    url: https://api.github.com/repos/rssnyder/<+execution.steps.pla.spec.configuration.configFiles.store.spec.repoName>/issues/<+trigger.prNumber>/comments
                    method: POST
                    headers:
                      - key: Accept
                        value: application/vnd.github+json
                      - key: Authorization
                        value: Bearer <+secrets.getValue("account.gh_pat")>
                      - key: X-GitHub-Api-Version
                        value: "2022-11-28"
                    outputVariables: []
                    requestBody: "{\"body\":\"Terraform Plan Successful: <+pipeline.executionUrl>\"}"
                  timeout: 10s
                  when:
                    stageStatus: Success
                    condition: <+trigger.event> == "PR"
                  failureStrategies: []
              - step:
                  type: HarnessApproval
                  name: approve
                  identifier: approve
                  spec:
                    approvalMessage: Please review the plan step output and approve based on the changes specified.
                    includePipelineExecutionHistory: true
                    approvers:
                      userGroups:
                        - _project_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
                  when:
                    stageStatus: Success
                    condition: <+pipeline.stages.apply.spec.execution.steps.pla.plan.detailedExitCode> != 0
                  failureStrategies: []
              - step:
                  type: TerraformApply
                  name: apply
                  identifier: apply
                  spec:
                    configuration:
                      type: InheritFromPlan
                    provisionerIdentifier: harnessascode
                  timeout: 10m
                  failureStrategies: []
                  when:
                    stageStatus: Success
                    condition: (<+pipeline.stages.apply.spec.execution.steps.pla.spec.configuration.configFiles.store.spec.branch> == "main") && (<+pipeline.stages.apply.spec.execution.steps.pla.plan.detailedExitCode> != 0)
        tags: {}
  storeType: INLINE
  delegateSelectors:
    - ecs
