pipeline:
  name: harness as code
  identifier: harness_as_code
  projectIdentifier: Default_Project_1662659562703
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: aws creds
        identifier: aws_creds
        template:
          templateRef: account.generate_and_save_aws_keys
          versionLabel: "1"
          gitBranch: main
    - stage:
        name: tf
        identifier: tf
        description: ""
        type: IACM
        spec:
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 5m
                  spec:
                    command: init
              - step:
                  type: Run
                  name: tflint
                  identifier: tflint
                  spec:
                    connectorRef: account.harnessImage
                    image: ghcr.io/terraform-linters/tflint
                    shell: Sh
                    command: tflint
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 5m
                  spec:
                    command: plan
              - step:
                  type: Run
                  name: checkov
                  identifier: checkov
                  spec:
                    connectorRef: account.harnessImage
                    image: bridgecrew/checkov
                    shell: Sh
                    command: checkov -f <+pipeline.stages.tf.spec.execution.steps.plan.output.outputVariables.plan>
              - step:
                  type: Run
                  name: tfsec
                  identifier: tfsec
                  spec:
                    connectorRef: account.harnessImage
                    image: aquasec/tfsec
                    shell: Sh
                    command: tfsec --soft-fail .
              - step:
                  type: IACMApproval
                  name: approve
                  identifier: approve
                  spec: {}
                  timeout: 5m
                  when:
                    stageStatus: Success
                    condition: <+trigger.event> != "PR"
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  timeout: 5m
                  spec:
                    command: apply
                  when:
                    stageStatus: Success
                    condition: <+trigger.event> != "PR"
          workspace: <+input>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        tags: {}
        delegateSelectors:
          - ecs
